apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-frontend
  template:
    metadata:
      labels:
        app: chatbot-frontend
    spec:
      containers:
      - name: frontend
        image: IMAGE_PLACEHOLDER
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: BACKEND_HOST
          value: "chatbot-backend-service"
        - name: BACKEND_PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-frontend-service
spec:
  selector:
    app: chatbot-frontend
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30001
  type: NodePort
